-- phpMyAdmin SQL Dump
-- version 4.6.6deb5
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: Sep 15, 2019 at 12:59 AM
-- Server version: 5.7.27-0ubuntu0.18.04.1
-- PHP Version: 7.2.19-0ubuntu0.18.04.2

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `etd-finalize`
--

-- --------------------------------------------------------

--
-- Table structure for table `failed_jobs`
--

CREATE TABLE `failed_jobs` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `connection` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `queue` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `payload` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `exception` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `failed_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------

--
-- Table structure for table `migrations`
--

CREATE TABLE `migrations` (
  `id` int(10) UNSIGNED NOT NULL,
  `migration` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `batch` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `migrations`
--

INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES
(1, '2014_10_12_000000_create_users_table', 1),
(2, '2014_10_12_100000_create_password_resets_table', 1),
(3, '2019_08_19_000000_create_failed_jobs_table', 1),
(4, '2019_09_14_163825_create_resources_table', 1);

-- --------------------------------------------------------

--
-- Table structure for table `password_resets`
--

CREATE TABLE `password_resets` (
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `token` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------

--
-- Table structure for table `resources`
--

CREATE TABLE `resources` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `code` int(11) NOT NULL,
  `batch` int(11) NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `rollnumber` int(11) NOT NULL,
  `tags` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `year` int(11) NOT NULL,
  `title` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `topic` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `company` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `supervisor` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `abstract` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `resources`
--

INSERT INTO `resources` (`id`, `code`, `batch`, `name`, `rollnumber`, `tags`, `year`, `title`, `topic`, `company`, `supervisor`, `abstract`, `created_at`, `updated_at`) VALUES
(1, 910, 18, 'Ei Nandar Aung', 1, 'MBA', 2015, 'A Study on Service Quality of Gandawun Shwe Bagan Travels & Tours Company', 'Service Quality', 'Gandawun Shwe Bagan', 'Daw Hla Hla Mon', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).', NULL, NULL),
(2, 911, 18, 'Aunt Htoo Aung', 2, 'MBA', 2015, 'A Study on Recruitment and Selection Practices of Myanmar Hand in Hand Marketing Services Co., Limited', 'Recruitment & Selection', 'Myanmar Hand in Hand ', 'Dr. Myint Myint Kyi', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).', NULL, NULL),
(3, 912, 18, 'Htoo Htoo Aung', 3, 'MBA', 2015, 'A Study on Employee Motivational Factors of Ruby True Hotel', 'Employee Motivation', 'Ruby True Hotel', 'Dr. Aye Thu Htun', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).', NULL, NULL),
(4, 913, 18, 'Thet Mar Aung', 4, 'MBA', 2015, 'A Study on Employee Motivational of Myanmar Oriental Bank in Yangon', 'Employee Motivation', 'Myanmar Oriental Bank', 'Dr. Moe Moe Khaing', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).', NULL, NULL),
(5, 914, 18, 'May Phoo Pwint Aung', 5, 'MBA', 2015, 'A Study on Promotion Mix of Grand Master International Co., Limited', 'Promotion Mix', 'Grand Master ', 'Daw Tin Tin Aye', '', NULL, NULL),
(6, 915, 18, 'Wint Sandar Aung', 6, 'MBA', 2015, 'A Study on Employee Motivation of Zeya & Associates Co., Limited', 'Employee Motivation', 'Zeya & Associates', 'Daw Hla Hla Mon', '', NULL, NULL),
(7, 916, 18, 'Thiha Aung', 8, 'MBA', 2015, 'A Study on Customer Satisfaction of Pact Global Microfinance Fund', 'Customer Satisfaction', 'Pact Global Microfinance', 'Dr. Myint Myint Kyi', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English.', NULL, NULL),
(8, 917, 18, 'Hein Thu Aung', 9, 'MBA', 2015, 'A Study on Recruitment and Selection of Device Service Co., Limited', 'Recruitment & Selection', 'Device ', 'Dr. Aye Thu Htun', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.', NULL, NULL),
(9, 918, 18, 'Thet Mon Aye', 10, 'MBA', 2015, 'A Study on Attitudes of Retailers to work Oraser KIT', 'Attitudes of Retailers', 'Orasel KIT', 'Dr. Tun Aung', 'It is a long established fact that a reader will be distracted .', NULL, NULL),
(10, 919, 18, 'Yu Ya Nyein Aye', 11, 'MBA', 2015, 'A Study on Recruitment and Selection of Kandawgyi Palace Hotel', 'Recruitment & Selection', 'Kandawgyi Palace Hotel', 'Dr. Aye Thu Htun', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).', NULL, NULL),
(11, 920, 18, 'Su Ei Lei', 12, 'MBA', 2015, 'A Study on Customer Relationship Management of ACE data Systems Limited', 'CRM', 'ACE data', 'Daw Hla Hla Mon', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).', NULL, NULL),
(12, 921, 18, 'Aung Myo Han', 13, 'MBA', 2015, 'A Study on Customer Relationship Management of American Vision', 'CRM', 'American Vision', 'Dr. Myint Myint Kyi', '', NULL, NULL),
(13, 922, 18, 'Ei Ei Hlaing', 14, 'MBA', 2015, 'A Study on Recruitment and Selection of Academy Hospital', 'Recruitment & Selection', 'Academy Hospital', 'Daw Winne Tun', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).', NULL, NULL),
(14, 923, 18, 'May Thanda Hlaing', 15, 'MBA', 2015, 'A Study on Service Quality of Myanmar Oriental Bank Limited', 'Service Quality', 'MOB', 'Dr. Tun Aung', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).', NULL, NULL),
(15, 924, 18, 'Zin Mar Hnin', 16, 'MBA', 2015, 'A Study on Customer Relationship Management of Myanmar Info Tech', 'CRM', 'Myanmar Info Tech', 'Dr. Aye Thandar Soe', '', NULL, NULL),
(16, 925, 18, 'Su Myat Thinzar Hnin', 17, 'MBA', 2015, 'A Study on Promotion Mix of Dennis Martin Watch', 'Promotion Mix', 'Dennis Martin', 'Daw Tin Tin Aye', '', NULL, NULL),
(17, 926, 18, 'Khaing Htay', 18, 'MBA', 2015, 'Influencing factors on Organizational Buying Decision in Black MATPE', 'Organizational Buying Decision', 'Black MATPE', 'Dr. Aye Thandar Soe', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).', NULL, NULL),
(18, 927, 18, 'Nilar Htay', 19, 'MBA', 2015, 'A Study on Employee Retention Management of Mega Lifescience Public Co., Limited', 'Employee Retention Management', 'Mega Lifescience ', 'Dr. Aye Thandar Soe', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).', NULL, NULL),
(19, 928, 18, 'Pyae Phyo Htet', 20, 'MBA', 2015, 'A Study on Consumers\' Buying Decision Making of Solar Power Products', 'Consumer Buying Decision Making', 'Solar Power Product', 'Dr. Moe Moe Khaing', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).', NULL, NULL),
(20, 929, 18, 'Soe Pyae Pyae Htoo', 21, 'MBA', 2015, 'A Study on Training and Development of Myanmar Industrial Port (MIP)', 'Training & Development', 'Myanmar Industrial Port', 'Dr. Myint Myint Kyi', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).', NULL, NULL),
(21, 930, 18, 'Su Yupar Htwe', 22, 'MBA', 2015, 'A Study on Performance of Bright Light Microfinance Co-operative Limited', 'Performance Study', 'Bright Light Microfinance Co-op ', 'Dr. Moe Moe Khaing', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy.', NULL, NULL),
(22, 931, 18, 'Ingyin', 23, 'MBA', 2015, 'A Study on Customer Relationship Mangement of Zeya & Associates Company Limited', 'CRM', 'Zeya & Associates', 'Daw Tin Tin Aye', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy.', NULL, NULL),
(23, 932, 18, 'Kathy', 24, 'MBA', 2015, 'A Study on Cabin Crew Training Programs of Asian Wings Airways', 'Training Programs', 'Asian Wings Airways', 'Dr. Myint Myint Kyi', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).', NULL, NULL),
(24, 933, 18, 'Ei Thinzar Khine', 25, 'MBA', 2015, 'A Study on Production Process of Eternal Sunshine Company Limited', 'Production Process', 'Eternal Sunshine Co.,Ltd', 'Dr. Moe Moe Khaing', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).', NULL, NULL),
(25, 934, 18, 'Htoo Eindra Kyaw', 26, 'MBA', 2015, 'A Study on Production Process of Power Wing Pile Co.,Ltd', 'Production Process', 'Power Wing Pile Co.,Ltd', 'Daw Tin Tin Aye', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).', NULL, NULL),
(27, 936, 18, 'Myat Mon Mon Kyaw', 28, 'MBA', 2015, 'A Study on Service Quality of Sedona Hotel ', 'Service Quality', 'Sedona Hotel ', 'Daw Hla Hla Mon', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).', NULL, NULL),
(28, 937, 18, 'Shune Yee Kyaw', 29, 'MBA', 2015, 'A Study on Consumer Buying Decision Making on European Luxury Automobiles', 'Consumer Buying Decision Making', 'European Luxury Automobiles', 'Dr. Aye Thu Htun', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).', NULL, NULL),
(29, 938, 18, 'Htet Aung Kyi', 30, 'MBA', 2015, 'Training and Development practices of Green Cross Hospital', 'Training and Development pracitces', 'Green Cross Hospital', 'Dr. Myint Myint Kyi', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).', NULL, NULL),
(30, 939, 18, 'Su Pyae Linn', 31, 'MBA', 2015, 'A Study on Job Satisfaction of Employees in International Beverages Training Co.,Ltd. (IBTC)', 'Employee Job Satisfaction', 'International Beverages', 'Dr. Khine Mar Hlaing', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).', NULL, NULL),
(31, 940, 18, 'Tin Htoo Lu', 32, 'MBA', 2015, 'A Study on Employee Motivation of Sakura Hospital', 'Employee Motivation', 'Sakura Hospital', 'Daw Tin Tin Aye', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).', NULL, NULL),
(32, 941, 18, 'Nang Ei Mon San Lwin', 33, 'MBA', 2015, 'A Study on Employee Motivation of UMH Company Limited', 'Employee Motivation', 'UMH Company Limited', 'Daw Winne Tun', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).', NULL, NULL),
(33, 942, 18, 'Thiri Winn Maung', 35, 'MBA', 2015, 'A Study on Recuritment and Selection Practices of Max Myanmar Construction Company', 'Recruitment & Selection', 'Max Myanamar Construction Co', 'Daw Winne Tun', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).', NULL, NULL),
(35, 944, 18, 'Khin Oo May', 37, 'MBA', 2015, 'A Study on  Employee Motivation of Green River Construction and Engineering Co.,Ltd', 'Employee Motivation', 'Green River Construciton & Eng', 'Daw Winne Tun', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).', NULL, NULL),
(36, 945, 18, 'May Myint Mo', 38, 'MBA', 2015, 'A Study on Training and Development of Asia Green Development Bank Ltd.', 'Training and Development', 'AGD Bank', 'Dr. Aye Thandar Soe', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).', NULL, NULL),
(37, 946, 18, 'Poe Ei Yin Mon', 39, 'MBA', 2015, 'A Study on Employee Motivation of Red Dragon Food Industry', 'Employee Motivation', 'Red Dragon Food Industry', 'Dr. Aye Thu Htun', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).', NULL, NULL),
(38, 947, 18, 'Htoo Aung Myat ', 40, 'MBA', 2015, 'Competitive Analysis on Myanmar Macadamia Business', 'Marketing Mix', 'Chimera Trading', 'Daw Hla Hla Mon', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).', NULL, NULL),
(39, 948, 18, 'Saw Mya Nwe', 42, 'MBA', 2015, 'A Study on Recruitment and Selection in Myanamar Information Technology PTE Ltd.', 'Recruitment & Selection', 'Myanmar Info Tech', 'Daw Tin Tin Aye', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).', NULL, NULL),
(40, 949, 18, 'Thal Su Nwe', 43, 'MBA', 2015, 'A Study on Compensation and Benefits of Loi Hein Co.,Ltd', 'Compenstion and Benefits', 'Loi Hein Co.,Ltd', 'Dr. Aye Thandar Soe', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).', NULL, NULL),
(41, 950, 18, 'Hay Mann Oo', 45, 'MBA', 2015, 'A Study on Recuritment and Selection of Myanamr Oriental Bank Limited', 'Recruitment & Selection', 'Myanmar Oriental Bank', 'Dr. Tun Aung', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).', NULL, NULL),
(42, 951, 18, 'Khaing Zin Oo', 46, 'MBA', 2015, 'A Study on Training and Development of Loi Hein Co.,Ltd', 'Training and Development', 'Loi Hein Co.,Ltd', 'Daw Tin Tin Aye', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).', NULL, NULL),
(43, 18, 19, 'Ye Lwin', 3, 'OMBA', 2016, 'Leadership style in Football clubs of Manyamar National League', 'Leadership Style', 'Myanamr National League', 'Dr. Moe Moe Khaing', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).', NULL, NULL),
(44, 19, 19, 'Thet Thet Myint', 84, 'OMBA', 2016, 'A Study on Project Management of Royal River View Condominium Project', 'Project Management', 'Royal River View Condominium ', 'Daw Winne Tun', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).', NULL, NULL),
(45, 20, 19, 'Yin Kay Khaing', 70, 'OMBA', 2016, 'A Study on Service Quality of the Hotel at Tharabar Gate', 'Service Quality', 'Hotel', 'Dr. Myint Myint Kyi', '', NULL, NULL),
(46, 21, 19, 'Thazin Toe', 110, 'OMBA', 2016, 'A Study on Risk Management of Ayeyarwady Bank', 'Risk Management', 'Ayeyarwady Bank', 'Daw Hla Hla Mon', '', NULL, NULL),
(47, 22, 19, 'Ye Lynn Zaw', 51, 'OMBA', 2016, 'A Study on Customer Relationship mgt of Direct 2U Co.,Ltd', 'Customer Relationship Mgt', 'Direct Zu', 'Dr. Aye Thandar Soe', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).', NULL, NULL),
(48, 23, 19, 'Chan Myae Shein', 11, 'OMBA', 2016, 'A Study on Marketing Mix of premier coffee company limited', 'Marketing Mix', 'Premier Coffee', 'Daw Winne Tun', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).', NULL, NULL),
(49, 24, 19, 'Zaw Htwe', 29, 'OMBA', 2016, 'Waiting line at toll gate of no.3 Yangon Naypyitaw Highway Junction', 'Waiting Line', 'Toll gate', 'Dr. Myint Myint Kyi', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).', NULL, NULL),
(50, 25, 19, 'Khin Thet Tun', 5, 'OMBA', 2016, 'A study on Service Quality of Pen Hlaing Hospital', 'Service Quality', 'Pen hlaing Hospital', 'Dr. Myint Myint Kyi', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).', NULL, NULL),
(51, 26, 19, 'Phyo Thiri Maung', 69, 'OMBA', 2016, 'A study on Training and development of Summit Park view Hotel (Ygn)', 'Training and development', 'Summit Parkview Hotel\\', 'Dr. Moe Moe Khaing', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).', NULL, NULL),
(52, 27, 19, 'Khin Nilar Aung', 13, 'OMBA', 2016, 'A study on Franchising of Myanmar Computer co.,Ltd (MCC)', 'Franhchising', 'Myanmar Computer', 'Dr. Aye Thandar Soe', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).', NULL, NULL),
(53, 28, 19, 'Nila Oo', 48, 'OMBA', 2016, 'A study on training programs of Sun Far Travels and tours Co.,Ltd', 'Training programs', 'Sun Far Travels and Tours', 'Daw Winne Tun', '', NULL, NULL),
(54, 29, 19, 'Kyu Kyu win', 56, 'OMBA', 2015, 'A study on Service Quality of Allen & Gledhill (Myanamr) Co.,Ltd', 'Service Quality', 'Allen and Gledhill', 'Dr. Aye Thu Htun', '', NULL, NULL),
(55, 30, 18, 'Ei Ei Aung', 119, 'OMBA', 2015, 'Financial Performance of Golden Key Family Co.,Ltd', 'Financial Performance', 'Golden Key family', 'Dr. Aye Thandar Soe', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).', NULL, NULL),
(56, 670, 11, 'Myo Hlaing Aung', 1, 'EMBA', 2015, 'A Study on Branch Awareness of 7 Day News Journal', 'Brand Awareness', '7 Day News Journal', 'Daw Winne Htun', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).', NULL, NULL),
(57, 671, 11, 'Than Htay Aung', 2, 'EMBA', 2017, 'Analysis on Service Quality of Chimera Trading', 'Service Quality', 'Chimera Trading', 'Daw Winne Htun', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English.', NULL, NULL),
(58, 672, 11, 'Htet Phone Aung', 3, 'EMBA', 2017, 'Awareness and Attitudes of MBA Students on Corporate Social Responsibility', 'Corporate Social Responsibility', 'MBA Students', 'Dr.Moe Moe Khaing', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English.', NULL, NULL),
(59, 673, 11, 'ThinzarAung', 4, 'EMBA', 2017, 'A Study on Service Quality of Home Medicare Service', 'Service Quality', 'Home Medicare Service', 'Dr.Aye Thu Htun', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).', NULL, NULL),
(60, 674, 11, 'Yan Aung', 5, 'EMBA', 2017, 'A Study on Central Bank Construction project of Myanmar Engineering Group Construction Co.Ltd', 'Central Bank Construction project', 'Myanmar Engineering Group\r\nContruction company limited', 'Daw Tin Tin Aye', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).', NULL, NULL),
(61, 675, 11, 'Hnin Moe Aye', 6, 'EMBA', 2017, 'Employee Motivation of Grand Power Machinery company limited', 'Employee Motivation', 'Grand Power Machinery Company', 'Daw Hla Hla Mon', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).', NULL, NULL),
(62, 676, 11, 'Lwin Lwin Nyein Chan', 7, 'EMBA', 2017, 'Utilization of Information and Communication Technology (ICT) solutions in small and medium retail business in Yangon', 'Information and Communication \r\nTechnology', 'Small and Medium retail business', 'Daw Hla Hla Mon', '', NULL, NULL),
(63, 677, 11, 'Thein Han ', 9, 'EMBA', 2017, 'A Study on Training programme of 7 Day Media', 'Traning Program', '7 Day Media', 'Daw Tin Tin Aye', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).', NULL, NULL),
(64, 678, 11, 'Shwe Pyi Hein', 10, 'EMBA', 2017, 'A Study on Training and Development practices of Sakura Hospital in Yangon', 'Training and Development practices', 'Sakura Hospital', 'Daw Winne Htun', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).', NULL, NULL),
(65, 679, 11, 'Zar Chi Tin Hla', 11, 'EMBA', 2017, 'A Study on employee motivation of First National Insurance Public Co.ltd', 'Employee Motivation', 'First National Insurance Public \r\nCo.ltd', 'Dr.Tun Aung', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).', NULL, NULL),
(66, 680, 11, 'Su Myat Hnin', 12, 'EMBA', 2017, 'A Study on Service Quality of Total Learning Academy', 'Service Quality', 'Total Learning Academy', 'Dr.Khine Mar Hlaing', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).', NULL, NULL),
(67, 681, 11, 'Chan Myae Shein', 13, 'EMBA', 2017, 'A Study on Service Quality of Hotel 7 Mile', 'Service Quality', 'Hotel 7 Mile', 'Daw Hla Hla Mon', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).', NULL, NULL),
(68, 682, 11, 'Tin Htut', 14, 'EMBA', 2017, 'A Study on project management of Tharkayta Housing project', 'Project Management', 'Tharkayta Housing Project', 'Dr.Khine Mar Hlaing', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).', NULL, NULL),
(69, 683, 11, 'Kyaw Kyaw Htwe', 15, 'EMBA', 2016, 'A Study on Cutomer Relionship Management of Myanmar International Blossom (MIB) Shipping and Logistics Company Limited', 'Customer Relationship Management', 'Myanmar International Blossom\r\n(MIB) Shipping and Logistics \r\nCompany Limited', 'Dr Aye Thanda Soe', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).', NULL, NULL),
(70, 684, 11, 'Yin Swe Khine @ \r\nSoe Soe Htwe', 16, 'EMBA', 2015, 'A  Study on Project Management of the Supply of Goods and related services for Thahtaychaung power transmission line project', 'Project Management', 'Goods and related services for Thahtaychaung power transmission line project', 'Dr Aye Thu Htun', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).', NULL, NULL);

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE `users` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email_verified_at` timestamp NULL DEFAULT NULL,
  `password` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `remember_token` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`id`, `name`, `email`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES
(1, 'drzymh', 'drzymh@gmail.com', NULL, '$2y$10$xOVHdYlTixcqxpiY82N1hui3lUKDv1RtvFWGTvH9DRQNfOH2e38PK', NULL, '2019-09-14 17:04:03', '2019-09-14 17:04:03'),
(2, 'ravi', 'ravi@gmail.com', NULL, '$2y$10$/5E/AAZfLmo9peecag8CROG7jCgtvyFFeVrZ/r3s5qn/QnIpObeBW', NULL, '2019-09-14 17:44:30', '2019-09-14 17:44:30'),
(3, 'zymh', 'zymh@gmail.com', NULL, '$2y$10$Wm2A3kCiWOuG9CQCvgkVVOcWufdQ9Oq1/zCAFGHwYQNY5bDeMLuuy', NULL, '2019-09-14 17:45:00', '2019-09-14 17:45:00');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `failed_jobs`
--
ALTER TABLE `failed_jobs`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `migrations`
--
ALTER TABLE `migrations`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `password_resets`
--
ALTER TABLE `password_resets`
  ADD KEY `password_resets_email_index` (`email`);

--
-- Indexes for table `resources`
--
ALTER TABLE `resources`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `users_email_unique` (`email`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `failed_jobs`
--
ALTER TABLE `failed_jobs`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT;
--
-- AUTO_INCREMENT for table `migrations`
--
ALTER TABLE `migrations`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;
--
-- AUTO_INCREMENT for table `resources`
--
ALTER TABLE `resources`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=71;
--
-- AUTO_INCREMENT for table `users`
--
ALTER TABLE `users`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=4;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
